---
title: "text.Rmd"
output: html_document
---


```{r, echo=FALSE, warning=FALSE, message=FALSE}
require('wordcloud')
require('biclust')
require('cluster')
require('igraph') 
require('dplyr')
require('scales')
require('SnowballC')
require('RColorBrewer')
require('ggplot2')
require('tm')
# source("https://bioconductor.org/biocLite.R")
# biocLite("Rgraphviz")
require('Rgraphviz')
require('fpc')
require('topicmodels')

setwd("C:\\Users\\HS\\Desktop\\school\\classes\\VIS\\HW_TEXT")
setwd("/Users/bobminnich/Documents/Columbia/Courses/DataVisualization/Edav-Text")
mypwd = file.path('source')

docs = Corpus(DirSource(mypwd))

#inspect(docs)

toSpace = content_transformer(function(yourdata, target) gsub(target, ' ', yourdata))
docs = tm_map(docs, toSpace, "/")
docs = tm_map(docs, toSpace, "@")
#docs = tm_map(docs, toSpace, "(")
#docs = tm_map(docs, toSpace, ")")
docs = tm_map(docs, toSpace, ";")
docs = tm_map(docs, toSpace, "--")

docs <- tm_map(docs, content_transformer(tolower))
docs = tm_map(docs, removeNumbers)
docs = tm_map(docs, removePunctuation)
docs = tm_map(docs, removeWords, stopwords("english"))
# docs = tm_map(docs, removeWords,c('school','department'))
docs = tm_map(docs,stemDocument)
docs = tm_map(docs,stripWhitespace)
docs = tm_map(docs,PlainTextDocument)

dtm = DocumentTermMatrix(docs)
tdm = TermDocumentMatrix(docs)


# mfreq = colSums(as.matrix(dtm[1:3, 1:dim(dtm)[2]]))
# Frequency of words
mfreq = colSums(as.matrix(dtm))
p1 = ggplot(subset(data.frame(word=names(mfreq),freq=mfreq),freq>40),aes(word,freq))+ geom_bar(stat='identity') + theme(axis.text.x=element_text(size=12,color='red',fac='bold.italic',angle=45,hjust=0.5))
#plot(p1)

set.seed(111) 
# Wordcloud
#wordcloud(names(mfreq),mfreq,
#          min.freq=5, # plot words apprear 10+ times
#          scale=c(4,0.5), # make it bigger with argument "scale"
#          colors=brewer.pal(8, "Dark2"), # use color palettes
#          random.color=FALSE, 
#          random.order=FALSE)

# frequency relationship
#plot(dtm,terms=findFreqTerms(dtm,lowfreq = 40),corThreshold = 0.5)


dtmc = removeSparseTerms(dtm,sparse=0.01) 
tdmc = removeSparseTerms(tdm,sparse=0.01)

mdist = dist(tdmc,method='euclidian')
mfit = hclust(d=mdist,method='ward.D2')

# clustering
# plot(mfit,hang=-1)
# rect.hclust(mfit,k=5,border='red')


mkm = kmeans(mdist,3)
# Clustering (k-means)
# clusplot(as.matrix(mdist),mkm$cluster,color=T,shade=T,labels=2,lines=0)

tdmc = removeSparseTerms(tdm,sparse=0.5)
dtm2 = as.DocumentTermMatrix(tdmc)
mlda = LDA(dtm2,k=5) #find k topics
mterms = terms(mlda,4) # find the first 4 terms of each topic

mterms = apply(mterms,MARGIN=2,paste,collapse=', ')
mtopic = topics(mlda,1)
mtopics = data.frame(doc=1:8,topic1=mtopic)

# Topic modeling
# qplot(doc,..count..,data=mtopics,geom='density',
#       fill=mterms[mtopic],position='stack')
```


## Speeches of George Washington (1789 - 1796)

<p style="text-align: left; font-size:20px; font-weight:bold;">Frequency of words</p>
```{r echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'}
plot(p1)
```

<p style="text-align: left; font-size:20px; font-weight:bold;">Wordcount</p>
```{r echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'}
wordcloud(names(mfreq),mfreq,
          min.freq=5,
          scale=c(4,0.5),
          colors=brewer.pal(8, "Dark2"),
          random.color=FALSE, 
          random.order=FALSE)
```

<p style="text-align: left; font-size:20px; font-weight:bold;">Relationship between words</p>
```{r echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'}
# Frequency between words
plot(dtm,terms=findFreqTerms(dtm,lowfreq = 40),corThreshold = 0.5)
```

<p style="text-align: left; font-size:20px; font-weight:bold;">Clustering</p>
```{r echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'}
# Clustering of words
plot(mfit,hang=-1)
rect.hclust(mfit,k=5,border='red')
```

<p style="text-align: left; font-size:20px; font-weight:bold;">Clustering (k-means) </p>
```{r echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'}
# Clustering (k-means)
clusplot(as.matrix(mdist),mkm$cluster,color=T,shade=T,labels=2,lines=0)
```

<p style="text-align: left; font-size:20px; font-weight:bold;">topic modeling </p>
```{r echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'}
# Topic modeling
qplot(doc,..count..,data=mtopics,geom='density',
      fill=mterms[mtopic],position='stack')
```

